import { Inter } from "@next/font/google";
import classNames from "classnames";
import Head from "next/head";
import Image from "next/image";

import styles from "@/styles/home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>前端工具箱</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classNames(styles.main)}>
        <span className="font-bold text-red-500">Layout</span>
        <h2 className={inter.className}>
          Docs <span>-&gt;</span>
        </h2>
        <p className={inter.className}>
          Find in-depth information about Next.js features and&nbsp;API.
        </p>
        <div>as</div>
      </div>
    </>
  );
}
